/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeliveryPanel.java
 *
 * Created on Jun 12, 2012, 6:59:26 AM
 */
package GUI;

import MStore.Product;
import MStore.ProductCatalog;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import mDB.DBConnection;

/**
 *
 * @author Hanzen
 */
public class DeliveryPanel extends javax.swing.JPanel {

    //init DeliveryPanel
    public void initDeliveryPanel(DBConnection db)
    {
        this.db = db;
        
        this.pCatalog = new ProductCatalog(this.db.getProdCatalog());
        this.initJTableList();
        
        this.upcList = new ArrayList();
        this.stockList = new ArrayList();
        this.productList = new ArrayList();
        
        this.dateLabel.setText(this.getDate());
        
    }
    
    public String getDate()
    {
           DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
           Date date = new Date();
           return dateFormat.format(date);
    }
    
    
    //init JTable
    public void initJTableList()
    {
        
         String data[][] = null;
         String col[] = {"UPC", "Item Description", "Quantity"};
         model= new DefaultTableModel(data,col)
         {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
         
        this.jTable1.setModel(model);
   
    }
    
   
    
    //add row to JTable
    public void addDataJTableList(Product prod, double qty)
    {
        
      this.model.insertRow(this.jTable1.getRowCount(),new Object[]{prod.getUPC(), prod.getDesciption(), qty});
   
      this.model.fireTableDataChanged();
      
      //scrolls the JTable at the bottom
      //source 
      //http://stackoverflow.com/questions/5956603/jtable-autoscrolling-to-bottom-problem
      //Rectangle rect = this.jTable1.getCellRect(this.jTable1.getRowCount(), 0, true);
      //Rectangle r2 = this.jTable1.getVisibleRect();
      
      //this.jTable1.scrollRectToVisible(new Rectangle(rect.x, rect.y, (int) r2.getWidth(), (int) r2.getHeight()));
      
    }
    
    //delete row to JTable
    public void removeDataJTableList(int row)
    {
        this.model.removeRow(row);
    }
    
    //clear all text field and Jtable
    public void clearAllTextField()
    {
        this.upcTextField.setText("");
        this.descTextField.setText("");
        this.qtyTextField.setText("");
        this.supplierTextField.setText("");
        
        this.upcList.clear();
        this.stockList.clear();
        this.productList.clear();
        this.initJTableList();
    }
    
    /** Creates new form DeliveryPanel */
    public DeliveryPanel() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CloseButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        upcTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        descTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        qtyTextField = new javax.swing.JTextField();
        InsertButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        supplierTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        lookUpFormButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        invoiceNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        CloseButton.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Add Inventory");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(CloseButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(CloseButton)
                .add(jLabel2))
        );

        jTable1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", ""},
                {"", "", ""},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        upcTextField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Insert Data");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("barcode");

        jLabel4.setText("Item Description");

        descTextField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        jLabel5.setText("Qty");

        qtyTextField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        InsertButton.setText("input");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(upcTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(descTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(qtyTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(9, 9, 9)
                        .add(InsertButton))
                    .add(jLabel1))
                .add(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(4, 4, 4)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(upcTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(descTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5)
                    .add(qtyTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(InsertButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel6.setText("Supplier's Name:");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        lookUpFormButton.setText("Look Up Form");
        lookUpFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookUpFormButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Invoice No.");

        invoiceNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceNumberActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Date:");

        dateLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(41, 41, 41)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 699, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(lookUpFormButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(deleteButton))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel6))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(invoiceNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(12, 12, 12)
                                .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(dateLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(supplierTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(submitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lookUpFormButton)
                    .add(deleteButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 368, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(invoiceNumber)
                    .add(jLabel8)
                    .add(dateLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(supplierTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(submitButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
}//GEN-LAST:event_CloseButtonActionPerformed

private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
// TODO add your handling code here:
    int key=-5;
    try{
    key = Integer.valueOf(this.upcTextField.getText());
    }catch(NumberFormatException e)
    {
        return;
    }
    
    String desc="";
    double stock;
    
    //means UPC contains in prodCatalog
    if(this.pCatalog.containsKey(key))
    {
        desc = this.descTextField.getText();
        try{
        stock = Double.valueOf(this.qtyTextField.getText());
        }catch(NumberFormatException e)
        {
         JOptionPane.showMessageDialog(this, "Quantity should be number");
         return;
        }
        
        this.addDataJTableList(this.pCatalog.getProduct(key), stock);
        
        //add item to ArrayList
        this.upcList.add(key);
        this.stockList.add(stock);
        this.productList.add(this.pCatalog.getProduct(key).getDesciption());
    }
    else
        JOptionPane.showMessageDialog(this, "UPC does not exists, add UPC number in add item menu first");
     
 //clears all text field
 this.upcTextField.setText("");
 this.descTextField.setText("");
 this.qtyTextField.setText("");

}//GEN-LAST:event_InsertButtonActionPerformed

private void lookUpFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookUpFormButtonActionPerformed
// TODO add your handling code here:
    
     this.pCatalog = new ProductCatalog(this.db.getProdCatalog());
     
     this.lookUpform.populateDataJTable(this.pCatalog.getCatalog());
     int n = JOptionPane.showConfirmDialog(null, this.lookUpform, "LOOK UP ITEM", JOptionPane.PLAIN_MESSAGE);
    
    if (n == JOptionPane.YES_OPTION)
    {
        int x=this.lookUpform.getSelectedItem();
        
        //returns -78 if nothing is selected
        if(x!=-78)
        {
            Product prod = this.pCatalog.getProduct(x);
            
            this.upcTextField.setText(String.valueOf(prod.getUPC()));
            this.descTextField.setText(prod.getDesciption());
         
        }
    }
    
}//GEN-LAST:event_lookUpFormButtonActionPerformed

private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
// TODO add your handling code here:
    
    if(this.jTable1.getSelectedRow() != -1 )
    {
        int row = this.jTable1.getSelectedRow();
        Integer key = (Integer) this.jTable1.getValueAt(row, 0);
        String product =(String) this.jTable1.getValueAt(row, 1);
        Double stock=(Double) this.jTable1.getValueAt(row, 2);
        
        this.upcList.remove(key);
        this.productList.remove(product);
        this.stockList.remove(stock);
        this.removeDataJTableList(this.jTable1.getSelectedRow());
    }
    else
        JOptionPane.showMessageDialog(this, "Please select an item to delete");
}//GEN-LAST:event_deleteButtonActionPerformed

private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
// TODO add your handling code here:
    
    if(this.supplierTextField.getText().equals("") && this.invoiceNumber.getText().equals(""))
    {
        JOptionPane.showMessageDialog(this, "Invoice and Supplier field cannot be empty");
        return;
    }
    
    //make sure items is not empty
    if(this.jTable1.getRowCount() !=0 )
    {
       int result = this.db.addDeliveryItem(this.upcList, this.stockList, this.productList, this.supplierTextField.getText(), this.invoiceNumber.getText());
       
       if(result==1)
       {
            //updates the currbalance
           int result2 =this.db.updateCurrBalance(this.upcList, this.stockList);
           if(result2 ==1)
             JOptionPane.showMessageDialog(this, "Successfully save to Database");
           else
             JOptionPane.showMessageDialog(this, "Something went wrong, wasn't able to save data"); 
       }
       else{
           JOptionPane.showMessageDialog(this, "Eror: Invoice number already existed, choose a different number");
           return;
       }
    this.clearAllTextField(); 
    }
    else
        JOptionPane.showMessageDialog(this, "Cannot submit an empty list");
    
    this.initJTableList();
    this.supplierTextField.setText("");
    this.invoiceNumber.setText("");

}//GEN-LAST:event_submitButtonActionPerformed

private void invoiceNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceNumberActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_invoiceNumberActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton InsertButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField descTextField;
    private javax.swing.JTextField invoiceNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton lookUpFormButton;
    private javax.swing.JTextField qtyTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField supplierTextField;
    private javax.swing.JTextField upcTextField;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel model;
    private ProductCatalog pCatalog;
    
    private DBConnection db;
    private LookUpForm lookUpform = new LookUpForm();
    
    private ArrayList upcList;
    private ArrayList stockList;
    private ArrayList productList;
}
